### PR TITLE
Django 3-2

### PR DESCRIPTION
**Pull request by will-moore**
App works fine with https://github.com/ome/omero-web/pull/356 - just removed the requirement `'Django>=1.11,<2.0'`

To test:
 - login
 - Should be redirected to 'courses' page (where Groups are listed as courses)

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#19](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/19/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/19/consoleText) for more details.
Possible conflicts:
  - PR #18 jburel 'pin omero-web'
    - setup.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1070](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1070/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1070/consoleText) for more details.
Possible conflicts:
  - PR #18 jburel 'pin omero-web'
    - setup.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#22](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/22/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/22/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - setup.py

--conflicts

**Comment by pwalczysko** [comment]
some conflicts to resolve

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#23](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/23/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/23/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - setup.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1073](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1073/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1073/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - setup.py

--conflicts

**Pull request merged**
